_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": linux-x86_64
dropout:
    value: 0.2
hidden_dim:
    value: 16
lr:
    value: 0.01
num_epochs:
    value: 200
num_heads:
    value: 1
num_layers:
    value: 2
output_dim:
    value: 3
